#!/bin/bash
#vps="zvur";
vps="aneka";

#if [[ $vps = "zvur" ]]; then
	#source="http://"
#else
	source="https://raw.githubusercontent.com/Vpaproject/d8"
#fi

# go to root
cd
#MYIP=$(wget -qO- ipv4.icanhazip.com);
# Install Pritunl
#!/bin/bash
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list
echo "deb http://repo.pritunl.com/stable/apt trusty main" > /etc/apt/sources.list.d/pritunl.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 42F3E95A2C4F08279C4960ADD68FA50FEA312927
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A
apt-get --assume-yes update
apt-get --assume-yes install pritunl mongodb-org
service pritunl start
#text gambar
apt-get install boxes

# text pelangi
sudo apt-get install ruby
sudo gem install lolcat

# text warna
cd
rm -rf /root/.bashrc
wget -O /root/.bashrc $source/master/.bashrc
# Install Client
echo "deb http://repo.pritunl.com/stable/apt trusty main" > /etc/apt/sources.list.d/pritunl.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A
apt-get update
apt-get install pritunl-client -y

#change time
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

# Install Squid
apt-get -y install squid3
cp /etc/squid3/squid.conf /etc/squid3/squid.conf.orig
wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/dathai/thaivpn.win/master/api/squid.conf" 
MYIP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | grep -v '192.168'`;
sed -i s/xxxxxxxxx/$MYIP/g /etc/squid3/squid.conf;
service squid3 restart
clear


# Install Web Server
apt-get -y install nginx php5-fpm php5-cli
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/dathai/thaivpn.win/master/api/nginx.conf"
mkdir -p /home/vps/public_html
echo "<pre>Setup by DRCYBER </pre>" > /home/vps/public_html/index.html
echo "<?php phpinfo(); ?>" > /home/vps/public_html/info.php
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/dathai/thaivpn.win/master/api/vps.conf"
sed -i 's/listen = \/var\/run\/php5-fpm.sock/listen = 127.0.0.1:9000/g' /etc/php5/fpm/pool.d/www.conf
service php5-fpm restart
service nginx restart

# install openvpn
clear
echo "Install OpenVPN"
cd
apt-get install openvpn -y
cd /etc/openvpn/
mkdir /etc/openvpn/keys
cd /etc/openvpn/keys
wget -O /etc/openvpn/keys/ca.crt "https://github.com/rlguia/debian-8.7-openvpn/raw/master/ca.crt"
wget -O /etc/openvpn/keys/dh1024.pem "https://github.com/rlguia/debian-8.7-openvpn/raw/master/dh1024.pem"
wget -O /etc/openvpn/keys/server.crt "https://github.com/rlguia/debian-8.7-openvpn/raw/master/server.crt"
wget -O /etc/openvpn/keys/server.key "https://github.com/rlguia/debian-8.7-openvpn/raw/master/server.key"
cd /etc/openvpn
rm -rfv /etc/openvpn/server.conf
wget -O /etc/openvpn/server.conf "https://github.com/rlguia/debian-8.7-openvpn/raw/master/server.conf"
wget -O /etc/openvpn/openvpn-auth-pam.so "https://github.com/rlguia/debian-8.7-openvpn/raw/master/openvpn-auth-pam.so"
/etc/init.d/openvpn restart

sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
iptables -t nat -I POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
iptables-save > /etc/iptables_yg_baru_dibikin.conf
wget -O /etc/network/if-up.d/iptables "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/iptables"
chmod +x /etc/network/if-up.d/iptables
/etc/init.d/openvpn restart

# Install Vnstat
apt-get -y install vnstat
vnstat -u -i eth0
sudo chown -R vnstat:vnstat /var/lib/vnstat
service vnstat restart

# Install Vnstat GUI
cd /home/vps/public_html/
wget https://raw.githubusercontent.com/dathai/thaivpn.win/master/api/vnstat_php_frontend-1.5.1.tar.gz
tar xf vnstat_php_frontend-1.5.1.tar.gz
rm vnstat_php_frontend-1.5.1.tar.gz
mv vnstat_php_frontend-1.5.1 vnstat
cd vnstat
sed -i "s/\$iface_list = array('eth0', 'sixxs');/\$iface_list = array('eth0');/g" config.php
sed -i "s/\$language = 'nl';/\$language = 'en';/g" config.php
sed -i 's/Internal/Internet/g' config.php
sed -i '/SixXS IPv6/d' config.php
cd

MYIP=$(wget -qO- ipv4.icanhazip.com);

# Enable Firewall
sudo ufw allow 22,80,81,222,443,3128,8080/tcp
sudo ufw allow 22,80,81,222,443,3128,8080/udp
sudo yes | ufw enable

#FIGlet In Linux
sudo apt-get install figlet
yum install figlet

# download script
cd
wget -O /usr/bin/benchmark $source/master/benchmark.sh
wget -O /usr/bin/speedtest $source/master/speedtest_cli.py
wget -O /usr/bin/ps-mem $source/master/ps_mem.py
wget -O /usr/bin/dropmon $source/master/dropmon.sh
wget -O /usr/bin/menu $source/master/menu.sh
wget -O /usr/bin/user-active-list $source/master/user-active-list.sh
wget -O /usr/bin/user-add $source/master/user-add.sh
wget -O /usr/bin/user-add-pptp $source/master/user-add-pptp.sh
wget -O /usr/bin/user-del $source/master/user-del.sh
wget -O /usr/bin/disable-user-expire $source/master/disable-user-expire.sh
wget -O /usr/bin/delete-user-expire $source/master/delete-user-expire.sh
wget -O /usr/bin/banned-user $source/master/banned-user.sh
wget -O /usr/bin/unbanned-user $source/master/unbanned-user.sh
wget -O /usr/bin/user-expire-list $source/master/user-expire-list.sh
wget -O /usr/bin/user-gen $source/master/user-gen.sh
wget -O /usr/bin/userlimit.sh $source/master/userlimit.sh
wget -O /usr/bin/userlimitssh.sh $source/master/userlimitssh.sh
wget -O /usr/bin/user-list $source/master/user-list.sh
wget -O /usr/bin/user-login $source/master/user-login.sh
wget -O /usr/bin/user-pass $source/master/user-pass.sh
wget -O /usr/bin/user-renew $source/master/user-renew.sh
wget -O /usr/bin/clearcache.sh $source/master/clearcache.sh
wget -O /usr/bin/bannermenu $source/master/bannermenu
wget -O /usr/bin/menu-update-script-vps.sh $source/master/menu-update-script-vps.sh
#cd

#echo "*/30 * * * * root service dropbear restart" > /etc/cron.d/dropbear
#echo "00 23 * * * root /usr/bin/disable-user-expire" > /etc/cron.d/disable-user-expire
#echo "0 */12 * * * root /sbin/reboot" > /etc/cron.d/reboot
##echo "00 01 * * * root echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a" > /etc/cron.d/clearcacheram3swap
#echo "0 */1 * * * root /usr/bin/clearcache.sh" > /etc/cron.d/clearcache1

cd
chmod +x /usr/bin/benchmark
chmod +x /usr/bin/speedtest
chmod +x /usr/bin/ps-mem
#chmod +x /usr/bin/autokill
chmod +x /usr/bin/dropmon
chmod +x /usr/bin/menu
chmod +x /usr/bin/user-active-list
chmod +x /usr/bin/user-add
chmod +x /usr/bin/user-add-pptp
chmod +x /usr/bin/user-del
chmod +x /usr/bin/disable-user-expire
chmod +x /usr/bin/delete-user-expire
chmod +x /usr/bin/banned-user
chmod +x /usr/bin/unbanned-user
chmod +x /usr/bin/user-expire-list
chmod +x /usr/bin/user-gen
chmod +x /usr/bin/userlimit.sh
chmod +x /usr/bin/userlimitssh.sh
chmod +x /usr/bin/user-list
chmod +x /usr/bin/user-login
chmod +x /usr/bin/user-pass
chmod +x /usr/bin/user-renew
chmod +x /usr/bin/clearcache.sh
chmod +x /usr/bin/bannermenu
chmod +x /usr/bin/menu-update-script-vps.sh
cd

# About
clear
figlet "THAIVPN"
echo "BY THAIVPN.WIN"
echo "-Pritunl"
echo "-MongoDB"
echo "-Squid Proxy Port 8080,3128"
echo "Vnstat     :  http://$MYIP:81/vnstat"
echo "Pritunl    :  https://$MYIP"
echo "Login pritunl?"
echo "copy key"
pritunl setup-key
